server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost/5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: root

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate_format-_sql: true

logging:
  level:
    hibernate:
      type: trace
